services:
  client-frontend:
    image: frontend:0.0.1
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app

  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      service-db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/podarok_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET=984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723g4
      - JWT_LIFETIME=24h
      - SPRING_MAIL_HOST=smtp.yandex.ru
      - SPRING_MAIL_PORT=465
      - SPRING_MAIL_USERNAME=podarOKService@yandex.ru
      - SPRING_MAIL_PASSWORD=fqvlkmzmqkklghwx
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=true

  service-db:
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres", "-d", "podarok_db"]
      interval: 1s
      timeout: 5s
      retries: 10
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: podarok_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  db-data:
  pgadmin-data: